name: Publish to npm

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write   # Allows the action to publish releases
  pages: write     # Allows the action to publish the GitHub Pages site
  id-token: write  # Required for OpenID Connect authentication (secure deployments)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'  # Speeds up builds

      - name: Install dependencies
        run: npm ci  # Safer for ci builds (vs npm install)

      - name: Build the package (Vite)
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Package dist files
        run: zip -r dist.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ""  # Changelog to be added after release
          draft: false
          prerelease: false
          files: dist.zip

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # Uploads the generated documentation to GitHub Pages


  deploy-pages:
    needs: publish  # Ensures deployment only happens after publishing
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4