name: Publish to npm

on:
  push:
    tags:
      - 'v*'
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'  # Speeds up builds

      - name: Install dependencies
        run: npm ci  # Faster than "npm install" for CI/CD

      - name: Build the package (Vite)
        run: npm run build

      - name: Generate Changelog
        run: |
          curl -sL https://github.com/git-chglog/git-chglog/releases/latest/download/git-chglog-linux-amd64 -o git-chglog
          chmod +x git-chglog
          ./git-chglog -o CHANGELOG.md

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog for ${{ github.ref_name }}"
          git push origin main

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md  # Use generated changelog
          draft: false
          prerelease: false
